// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitCountApi.Data;

#nullable disable

namespace VisitCountApi.Migrations
{
    [DbContext(typeof(VisitorCountContext))]
    [Migration("20250513124203_RemoveKeyFromEntityDailyVisit")]
    partial class RemoveKeyFromEntityDailyVisit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisitCountApi.Entities.DailyVisit", b =>
                {
                    b.Property<int>("PersianDateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersianDateID"));

                    b.Property<DateTime?>("InsertDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalVisits")
                        .HasColumnType("int");

                    b.HasKey("PersianDateID");

                    b.ToTable("DailyVisits");
                });

            modelBuilder.Entity("VisitCountApi.Entities.Visitor", b =>
                {
                    b.Property<Guid>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InstertDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<short>("VisitCount")
                        .HasColumnType("smallint");

                    b.HasKey("VisitId");

                    b.ToTable("Visitors");
                });
#pragma warning restore 612, 618
        }
    }
}
